### PR TITLE
Update institutional partners

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
@TomAugspurger is it OK (or can you check) to list you here for Continuum?

I have to check for Inria as well.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Yep, thanks.

**Comment by jorisvandenbossche** [comment]
@TomAugspurger updated this PR to make it Anaconda now instead of Continuum Analytics (or does it have to be Anaconda Inc. ?)

@GaelVaroquaux added Paris-Saclay CDS

Will do an accompanying PR to update the website

**Comment by pzwang** [comment]
"Anaconda, Inc." please!

**Comment by jorisvandenbossche** [comment]
OK, thanks for the note! will change

**Comment by jorisvandenbossche** [comment]
@pzwang to update the website (https://github.com/pandas-dev/pandas-website/pull/47), which logo should I use? Is this one OK: https://www.anaconda.com/wp-content/themes/anaconda/images/logo-dark.png ?

**Comment by TomAugspurger** [comment]
@jorisvandenbossche I uploaded a png to the other thread.

**Comment by GaelVaroquaux** [comment]
Great! Thanks Joris

**Pull request merged**
