### PR TITLE
Moving some core team members to inactive status

### PR DESCRIPTION
**Pull request by wesm**
I've contacted some of the inactive core team members about returning to active status, and the ones in this patch have indicated they do not intend to become active again.

Since the governance documents provide a 1 year grace period, I will wait to hear back from the others about what they would like to do.

In the meantime, if the current core team can vote:

- [+1] I support these changes
- [-1] I do not support these changes

My vote: +1

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@pandas-dev/pandas-core reminder! Can you all do a +1 / -1 on the post above?

**Comment by jreback** [comment]
+1

**Comment by jorisvandenbossche** [comment]
I think we have enough votes (6 here, plus the 3 that are OK with being removed), so merging this (so I can update the website PR). If others have replied in the meantime, we can always do a next PR.

**Comment by wesm** [comment]
+1

**Pull request merged**
