### PR TITLE
Added Brock to Anaconda

### PR DESCRIPTION
**Pull request by TomAugspurger**
cc @jbrockmendel

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@jorisvandenbossche does your information need to be updated?

**Comment by jorisvandenbossche** [comment]
> @jorisvandenbossche does your information need to be updated?

Yes, but I think for Wes as well? @wesm

**Comment by wesm** [comment]
Yes -- I have dual affiliation with RStudio and Ursa Labs

**Comment by TomAugspurger** [comment]
Joris, would I just put down Ursa Labs for you?

**Comment by wesm** [comment]
@TomAugspurger that's fine, thanks

**Comment by TomAugspurger** [comment]
OK

1. Wes has been removed from the Two Sigma list and added to Ursa Labs & RStudio
2. Joris added to Ursa Labs
3. Moved the Paris Saclay CDS to past institutions.

Merging later tonight if there are no objections.

**Pull request merged**
